In [2]:
import numpy as np

In [4]:
sales = [5,10,15,20]

sales_arr = np.array(sales)
sales_arr

array([ 5, 10, 15, 20])

In [5]:
type(sales_arr)

numpy.ndarray

In [7]:
print(f'ndim: {sales_arr.ndim}')
print(f'shape: {sales_arr.shape}')
print(f'size: {sales_arr.size}')
print(f'dtype: {sales_arr.dtype}')

ndim: 1
shape: (4,)
size: 4
dtype: int32


In [15]:
sales_nested = [[5,10,15],[15,20,25]]

In [16]:
sales_nested_arr = np.array(sales_nested)
sales_nested_arr

array([[ 5, 10, 15],
       [15, 20, 25]])

In [18]:
sales_nested_arr[1] + 1

array([16, 21, 26])

In [17]:
print(f'ndim: {sales_nested_arr.ndim}')
print(f'shape: {sales_nested_arr.shape}')
print(f'size: {sales_nested_arr.size}')
print(f'dtype: {sales_nested_arr.dtype}')

ndim: 2
shape: (2, 3)
size: 6
dtype: int32


In [19]:
sales_nested_arr.T

array([[ 5, 15],
       [10, 20],
       [15, 25]])