In [1]:
import numpy as np

In [2]:
sales = [5,10,15,20]

sales_arr = np.array(sales)
sales_arr

array([ 5, 10, 15, 20])

In [3]:
type(sales_arr)

numpy.ndarray

In [4]:
print(f'ndim: {sales_arr.ndim}')
print(f'shape: {sales_arr.shape}')
print(f'size: {sales_arr.size}')
print(f'dtype: {sales_arr.dtype}')

ndim: 1
shape: (4,)
size: 4
dtype: int32


In [5]:
sales_nested = [[5,10,15],[15,20,25]]

In [6]:
sales_nested_arr = np.array(sales_nested)
sales_nested_arr

array([[ 5, 10, 15],
       [15, 20, 25]])

### Arrays

In [7]:
sales_nested_arr[1] + 1

array([16, 21, 26])

In [8]:
print(f'ndim: {sales_nested_arr.ndim}')
print(f'shape: {sales_nested_arr.shape}')
print(f'size: {sales_nested_arr.size}')
print(f'dtype: {sales_nested_arr.dtype}')

ndim: 2
shape: (2, 3)
size: 6
dtype: int32


In [9]:
sales_nested_arr.T

array([[ 5, 15],
       [10, 20],
       [15, 25]])

In [10]:
np.zeros((3,4),dtype=int)


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.ones((3,4),dtype=int)


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [132]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [14]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [15]:
np.arange(1,9,2).reshape(2,2)

array([[1, 3],
       [5, 7]])

In [16]:
np.ones(2,dtype=int)

array([1, 1])

In [17]:
np.zeros(100,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.zeros(100,int).reshape(10,10)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [21]:
np.linspace(8,64,8)

array([ 8., 16., 24., 32., 40., 48., 56., 64.])

In [22]:
from numpy.random import default_rng

In [100]:
rng = default_rng(12345)

In [101]:
rng

Generator(PCG64) at 0x197FD2EAF80

In [114]:
rng.random(10)

array([0.08159457, 0.1598956 , 0.34010018, 0.46519315, 0.26642103,
       0.8157764 , 0.19329439, 0.12946908, 0.09166475, 0.59856801])

In [108]:
rng2 = np.random.default_rng(616)

In [115]:
rng2.random(10)


array([0.8520208 , 0.89723864, 0.80578865, 0.90879236, 0.37141849,
       0.41116148, 0.29953469, 0.35593281, 0.37394491, 0.03692463])

In [68]:
rng.integers(0,10,100)

array([4, 0, 0, 5, 0, 7, 5, 9, 9, 5, 7, 9, 2, 9, 7, 2, 0, 0, 9, 1, 0, 7,
       7, 2, 3, 1, 3, 9, 4, 6, 4, 9, 2, 3, 6, 1, 0, 1, 6, 9, 4, 1, 9, 8,
       7, 2, 1, 8, 9, 0, 1, 3, 9, 4, 2, 9, 4, 8, 4, 3, 1, 4, 6, 7, 0, 6,
       5, 8, 8, 6, 5, 5, 8, 9, 2, 3, 4, 3, 1, 3, 6, 4, 5, 0, 6, 4, 9, 3,
       5, 2, 5, 2, 1, 7, 5, 3, 2, 9, 5, 4], dtype=int64)

In [121]:
rng.normal(50,5,10)

array([48.88180537, 46.49154596, 41.02143412, 54.09162811, 47.14483549,
       50.00392763, 44.68178642, 56.5085725 , 53.73936471, 54.90437955])

In [129]:
rng = default_rng(12345)

random_ages = rng.integers(1,100,100)
random_ages

array([69, 22, 78, 31, 20, 79, 64, 67, 98, 39, 83, 33, 56, 59, 21, 18, 22,
       67, 61, 94, 70, 24, 91, 94, 73, 66, 13,  9, 26, 44,  7, 88, 47, 69,
       21, 32, 11, 73, 77, 22, 71,  8, 39, 15, 74, 34, 47, 46, 47, 26, 55,
       81, 49, 19,  2, 12,  8,  9, 12, 59, 80, 85, 65, 60, 33, 93, 64, 72,
       73, 86, 70, 92, 54, 54, 25, 93, 55, 49, 31, 27, 63, 45, 56, 66, 89,
       33, 68, 90, 45, 25, 29, 33, 62, 25, 83, 35,  6,  0,  2, 62],
      dtype=int64)

### Indexing & Slicing