In [1]:
import numpy as np

In [2]:
sales = [5,10,15,20]

sales_arr = np.array(sales)
sales_arr

array([ 5, 10, 15, 20])

In [3]:
type(sales_arr)

numpy.ndarray

In [4]:
print(f'ndim: {sales_arr.ndim}')
print(f'shape: {sales_arr.shape}')
print(f'size: {sales_arr.size}')
print(f'dtype: {sales_arr.dtype}')

ndim: 1
shape: (4,)
size: 4
dtype: int32


In [5]:
sales_nested = [[5,10,15],[15,20,25]]

In [6]:
sales_nested_arr = np.array(sales_nested)
sales_nested_arr

array([[ 5, 10, 15],
       [15, 20, 25]])

### Arrays

In [7]:
sales_nested_arr[1] + 1

array([16, 21, 26])

In [8]:
print(f'ndim: {sales_nested_arr.ndim}')
print(f'shape: {sales_nested_arr.shape}')
print(f'size: {sales_nested_arr.size}')
print(f'dtype: {sales_nested_arr.dtype}')

ndim: 2
shape: (2, 3)
size: 6
dtype: int32


In [9]:
sales_nested_arr.T

array([[ 5, 15],
       [10, 20],
       [15, 25]])

In [10]:
np.zeros((3,4),dtype=int)


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.ones((3,4),dtype=int)


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [14]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [15]:
np.arange(1,9,2).reshape(2,2)

array([[1, 3],
       [5, 7]])

In [16]:
np.ones(2,dtype=int)

array([1, 1])

In [17]:
np.zeros(100,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.zeros(100,int).reshape(10,10)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [21]:
np.linspace(8,64,8)

array([ 8., 16., 24., 32., 40., 48., 56., 64.])

In [22]:
from numpy.random import default_rng

In [23]:
rng = default_rng(12345)

In [24]:
rng

Generator(PCG64) at 0x24ADBD12260

In [25]:
rng.random(10)

array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
       0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287])

In [26]:
rng2 = np.random.default_rng(616)

In [27]:
rng2.random(10)


array([0.39682145, 0.86568572, 0.46040359, 0.30599848, 0.57381588,
       0.08888468, 0.88194347, 0.73228387, 0.73215182, 0.56233394])

In [28]:
rng.integers(0,10,100)

array([7, 2, 9, 9, 7, 6, 1, 0, 2, 4, 0, 8, 4, 6, 2, 3, 1, 7, 7, 2, 7, 0,
       3, 1, 7, 3, 4, 4, 4, 2, 5, 8, 4, 1, 0, 1, 0, 0, 1, 5, 8, 8, 6, 6,
       3, 9, 6, 7, 7, 8, 7, 9, 5, 5, 2, 9, 5, 4, 3, 2, 6, 4, 5, 6, 8, 3,
       6, 9, 4, 2, 2, 3, 6, 2, 8, 3, 0, 0, 0, 6, 3, 2, 6, 0, 5, 6, 0, 1,
       3, 3, 9, 4, 6, 1, 8, 2, 7, 4, 4, 4], dtype=int64)

In [29]:
rng.normal(50,5,10)

array([49.64364597, 52.37024865, 47.92573119, 50.4885825 , 41.79791082,
       45.71370588, 53.44140894, 44.22735208, 53.25226195, 43.05820024])

In [30]:
rng = default_rng(12345)

random_ages = rng.integers(1,100,100)
random_ages

array([70, 23, 79, 32, 21, 79, 64, 67, 98, 39, 84, 33, 57, 60, 22, 19, 23,
       67, 61, 94, 70, 25, 91, 94, 73, 67, 13, 10, 27, 44,  8, 88, 47, 70,
       22, 33, 12, 73, 77, 22, 71,  9, 39, 16, 74, 34, 47, 47, 48, 27, 56,
       81, 50, 20,  3, 13,  9, 10, 13, 60, 80, 85, 65, 60, 33, 93, 64, 72,
       73, 86, 70, 93, 54, 55, 25, 93, 55, 50, 32, 28, 63, 45, 57, 66, 90,
       33, 68, 90, 46, 26, 29, 34, 63, 26, 84, 36,  7,  1,  3, 63],
      dtype=int64)

### Indexing & Slicing

In [31]:
product_array = np.array(['fruits','vegetables','cereal','diary','eggs','snacks','coffe','tea'])

In [32]:
print(product_array)
print(product_array[1])
print(product_array[-1])
print(product_array[:5])
print(product_array[5:])


['fruits' 'vegetables' 'cereal' 'diary' 'eggs' 'snacks' 'coffe' 'tea']
vegetables
tea
['fruits' 'vegetables' 'cereal' 'diary' 'eggs']
['snacks' 'coffe' 'tea']


In [33]:
product_array2D = product_array.reshape(2,4)

In [34]:
product_array2D

array([['fruits', 'vegetables', 'cereal', 'diary'],
       ['eggs', 'snacks', 'coffe', 'tea']], dtype='<U10')

In [35]:
product_array2D[1,2]

'coffe'

In [36]:
product_array2D[1,0]

'eggs'

In [37]:
product_array2D[:,:2]

array([['fruits', 'vegetables'],
       ['eggs', 'snacks']], dtype='<U10')

In [38]:
int_array = np.arange(12)

In [39]:
int_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
print(int_array[1])
print(int_array[-1])

1
11


In [41]:
int_array[::2]

array([ 0,  2,  4,  6,  8, 10])

In [42]:
int_array2D = int_array.reshape(3,4)

In [43]:
int_array2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
int_array2D[0,:]

array([0, 1, 2, 3])

In [45]:
int_array2D[:,3]

array([ 3,  7, 11])

In [46]:
int_array2D[1,2]

6

In [47]:
ages = np.array([5, 10, 15, 19, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80])

In [48]:
youth_ages = ages[1:4]

In [49]:
adult_ages = ages[4:-3]

In [50]:
ages[-3:]

array([70, 75, 80])

In [51]:
rng = np.random.default_rng(616)

In [52]:
inventory = rng.integers(0,100,10)

In [53]:
inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [54]:
inventory - 24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33], dtype=int64)

In [55]:
inventory / 2

array([19.5, 19.5, 46.5, 43. , 24. , 23. , 24. , 15. ,  5.5, 28.5])

In [56]:
price = (rng.random(10) * 10).round(2)

In [57]:
print(price)
print(inventory)

[0.89 8.82 7.32 7.32 5.62 3.4  0.63 3.57 2.03 4.31]
[39 39 93 86 48 46 48 30 11 57]


In [58]:
price * inventory

array([ 34.71, 343.98, 680.76, 629.52, 269.76, 156.4 ,  30.24, 107.1 ,
        22.33, 245.67])

In [59]:
(price * inventory).sum()


2520.4700000000003

In [60]:
inventory_list = list(inventory)

In [61]:
print(inventory)
print(inventory_list)

[39 39 93 86 48 46 48 30 11 57]
[39, 39, 93, 86, 48, 46, 48, 30, 11, 57]


In [62]:
inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57], dtype=int64)

In [63]:
inventory_list

[39, 39, 93, 86, 48, 46, 48, 30, 11, 57]

In [64]:
town_a_ages = np.array([25, 45, 70, 34, 58])
town_b_ages = np.array([30, 55, 65, 40, 60])

age_differences = town_a_ages - town_b_ages

In [65]:
age_differences

array([ -5, -10,   5,  -6,  -2])

In [66]:
sales_arr = rng.integers(0,100,10)

In [67]:
sales_arr

array([94, 10, 27, 52, 15, 80, 90,  7, 32, 15], dtype=int64)

In [68]:
sales_arr != 94

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [69]:
sales_arr[sales_arr != 94]

array([10, 27, 52, 15, 80, 90,  7, 32, 15], dtype=int64)

In [70]:
sales_arr[(sales_arr >= 90) | (sales_arr == 10) ]

array([94, 10, 90], dtype=int64)

In [71]:
mask = (sales_arr >= 90) | (sales_arr == 10)
sales_arr[mask]

array([94, 10, 90], dtype=int64)

In [72]:
sales_array = np.array([0,5,155,0,518])

In [73]:
print(sales_array)
print(product_array[:5])
print(product_array[:5][sales_array > 0])

[  0   5 155   0 518]
['fruits' 'vegetables' 'cereal' 'diary' 'eggs']
['vegetables' 'cereal' 'eggs']


In [74]:
sales_array

array([  0,   5, 155,   0, 518])

In [75]:
my_array = np.arange(20)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [76]:
even_mask = my_array % 2 == 0

my_array[even_mask]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [77]:
even_odd = np.array(['even','odd'] * 10)
even_odd

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [78]:
even_odd != 'odd'

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [79]:
my_array[even_odd != 'odd']

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [80]:
my_array[even_odd != 'odd'] = 0
my_array

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [81]:
inventory_array = np.array([12,102,18,0,0])


In [82]:
product_array = product_array[:5]

In [83]:
product_array

array(['fruits', 'vegetables', 'cereal', 'diary', 'eggs'], dtype='<U10')

In [84]:
np.where(inventory_array <= 0, 'Out of stock','In Stock')

array(['In Stock', 'In Stock', 'In Stock', 'Out of stock', 'Out of stock'],
      dtype='<U12')

In [85]:
np.where(inventory_array <= 0,'Out of stock', product_array)

array(['fruits', 'vegetables', 'cereal', 'Out of stock', 'Out of stock'],
      dtype='<U12')

In [86]:
my_array

array([ 0,  1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0,
       17,  0, 19])

In [87]:
np.where(my_array % 2 == 0,'even','odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [88]:
np.where(my_array % 2 == 1)


(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int64),)

In [89]:
my_array[my_array % 2 == 0]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [90]:
np.where(my_array % 2 == 0, 'even', np.where(my_array == 9, my_array,'odd'))

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U11')

In [91]:
ages = np.array([25, 12, 15, 64, 35, 80, 45, 10, 22, 55])
np.where(ages >= 18)

(array([0, 3, 4, 5, 6, 8, 9], dtype=int64),)

In [92]:
rng = np.random.default_rng(616)
price = (rng.random(10) * 10).round(2)
inventory = rng.integers(0,100,10)
print(price)
print(inventory)

[3.97 8.66 4.6  3.06 5.74 0.89 8.82 7.32 7.32 5.62]
[80 33 60  6 31 35 16 20 29 43]


In [93]:
price.mean()

5.6

In [94]:
price.sum()


56.0

In [95]:
price.std()

2.407517393498955

In [96]:
(price * inventory)

array([317.6 , 285.78, 276.  ,  18.36, 177.94,  31.15, 141.12, 146.4 ,
       212.28, 241.66])

In [97]:
(price * inventory).sum()


1848.2900000000002

In [98]:
(price * inventory).argmin()


3

In [99]:
price_2d = price.reshape(5,2)
price_2d

array([[3.97, 8.66],
       [4.6 , 3.06],
       [5.74, 0.89],
       [8.82, 7.32],
       [7.32, 5.62]])

In [100]:
price_2d.sum(axis=0)

array([30.45, 25.55])

In [101]:
price_2d.sum(axis=1)


array([12.63,  7.66,  6.63, 16.14, 12.94])

In [102]:
sales_array = sales_arr.reshape(2,5)

In [103]:
print(sales_array)

[[94 10 27 52 15]
 [80 90  7 32 15]]


In [104]:
np.median(sales_array)

29.5

In [105]:
np.percentile(sales_array,50)

29.5

In [106]:
np.unique(sales_array)

array([ 7, 10, 15, 27, 32, 52, 80, 90, 94], dtype=int64)

In [107]:
np.sqrt(sales_array)

array([[9.69535971, 3.16227766, 5.19615242, 7.21110255, 3.87298335],
       [8.94427191, 9.48683298, 2.64575131, 5.65685425, 3.87298335]])

In [108]:
print(price)
print(inventory)
product_value = price * inventory
product_value.sort()
reshaped_product_value = product_value.reshape(2,5)
print(reshaped_product_value)

[3.97 8.66 4.6  3.06 5.74 0.89 8.82 7.32 7.32 5.62]
[80 33 60  6 31 35 16 20 29 43]
[[ 18.36  31.15 141.12 146.4  177.94]
 [212.28 241.66 276.   285.78 317.6 ]]


In [109]:
np.median(reshaped_product_value)

195.11

In [110]:
np.percentile(reshaped_product_value,50)

195.11

In [111]:
sales_array

array([[94, 10, 27, 52, 15],
       [80, 90,  7, 32, 15]], dtype=int64)

In [112]:
sales_array.sort()
sales_array


array([[10, 15, 27, 52, 94],
       [ 7, 15, 32, 80, 90]], dtype=int64)

In [113]:
sales_array.sort(axis=0)
sales_array

array([[ 7, 15, 27, 52, 90],
       [10, 15, 32, 80, 94]], dtype=int64)

In [114]:
sales_array.sort(axis=1)
sales_array

array([[ 7, 15, 27, 52, 90],
       [10, 15, 32, 80, 94]], dtype=int64)

In [115]:
product_value

array([ 18.36,  31.15, 141.12, 146.4 , 177.94, 212.28, 241.66, 276.  ,
       285.78, 317.6 ])

In [116]:
# copy table
np.sort(product_value) 

array([ 18.36,  31.15, 141.12, 146.4 , 177.94, 212.28, 241.66, 276.  ,
       285.78, 317.6 ])